import React,{useEffect,useState} from 'react';
import {LayoutDashboard,CalendarDays,Users,Scissors,UserRound,Receipt,Wallet,Package,Percent,BarChart3,MessageCircle,Settings,ArrowUpRight,Plus,X,Download} from 'lucide-react';
import {siteData} from '../data/siteData';
import {available,today,money,orderTotals,cashExpected,commissionRows,statusOptions} from './model';
import '../styles/demo.css';
import './crm.css';
const tabs=[['Visão geral',LayoutDashboard],['Agenda',CalendarDays],['Clientes',Users],['Comandas',Receipt],['Caixa',Wallet],['Serviços',Scissors],['Equipe',UserRound],['Comissões',Percent],['Estoque',Package],['Relacionamento',MessageCircle],['Relatórios',BarChart3],['Configurações',Settings]];
const BR=d=>d?d.slice(0,10).split('-').reverse().join('/'):'—';
const dateOf=stamp=>{const d=new Date(stamp);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const cents=value=>Math.round(Number(value||0)*100);
const field=(name,label,type='text',extra={})=>({name,label,type,...extra});
function Modal({title,onClose,children}){useEffect(()=>{const key=e=>{if(e.key==='Escape')onClose();};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[onClose]);return <div className="crm-overlay"><section className="crm-modal" role="dialog" aria-modal="true" aria-label={title}><div className="crm-modal-title"><h2>{title}</h2><button type="button" onClick={onClose} aria-label="Fechar janela"><X size={22}/></button></div>{children}</section></div>;}
function Form({fields,initial={},onSubmit,submit='Salvar',busy=false}){const [values,setValues]=useState(initial);return <form className="crm-form" onSubmit={e=>{e.preventDefault();onSubmit(values);}}>{fields.map(f=><label key={f.name}>{f.label}{f.type==='select'?<select required={f.required!==false} value={values[f.name]??''} onChange={e=>setValues({...values,[f.name]:e.target.value})}><option value="">Selecione</option>{f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='textarea'?<textarea maxLength={2000} value={values[f.name]??''} onChange={e=>setValues({...values,[f.name]:e.target.value})}/>:f.type==='checkbox'?<input type="checkbox" checked={!!values[f.name]} onChange={e=>setValues({...values,[f.name]:e.target.checked})}/>:<input autoFocus={fields[0]===f} required={f.required!==false} type={f.type} min={f.min} max={f.max} step={f.step} maxLength={f.type==='tel'?18:120} value={values[f.name]??''} onChange={e=>setValues({...values,[f.name]:e.target.value})}/>}</label>)}<button disabled={busy} className="demo-primary" type="submit">{busy?'Salvando…':submit}</button></form>;}
function Panel({title,action,children}){return <section className="demo-panel"><div className="demo-panel-title"><h2>{title}</h2>{action}</div>{children}</section>;}
function Table({headers,children,empty}){return <div className="demo-table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table>{empty&&<p className="demo-empty">Nenhum registro encontrado.</p>}</div>;}
function Stats({items}){return <div className="demo-metrics">{items.map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div>;}
function Status({value}){return <span className={`crm-badge badge-${value.replaceAll(' ','-')}`}>{value}</span>;}
function AppointmentForm({data,initial={},onSubmit,busy}){const [v,setV]=useState({clientId:'',serviceId:data.services.find(s=>s.active)?.id||'',professionalId:'',date:today(),time:'',notes:'',...initial});const slots=available(data,{...v,excludeId:initial.id});return <form className="crm-form" onSubmit={e=>{e.preventDefault();onSubmit(v);}}><label>Cliente<select required value={v.clientId} onChange={e=>setV({...v,clientId:e.target.value})}><option value="">Selecione um cliente</option>{data.clients.map(c=><option key={c.id} value={c.id}>{c.name} · {c.phone}</option>)}</select></label><label>Serviço<select required value={v.serviceId} onChange={e=>setV({...v,serviceId:e.target.value,professionalId:'',time:''})}>{data.services.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name} · {s.duration} min · {money(s.price)}</option>)}</select></label><label>Profissional<select required value={v.professionalId} onChange={e=>setV({...v,professionalId:e.target.value,time:''})}><option value="">Selecione um profissional</option>{data.team.filter(p=>p.active&&p.services.includes(v.serviceId)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Data<input type="date" min={today()} required value={v.date} onChange={e=>setV({...v,date:e.target.value,time:''})}/></label><fieldset><legend>Horários livres</legend><div className="demo-slots">{slots.map(t=><button type="button" key={t} aria-pressed={v.time===t} onClick={()=>setV({...v,time:t})}>{t}</button>)}</div>{!slots.length&&<p className="crm-muted">Escolha o profissional e uma data com expediente livre.</p>}</fieldset><label>Observações<textarea maxLength={2000} value={v.notes} onChange={e=>setV({...v,notes:e.target.value})}/></label><button className="demo-primary" disabled={busy||!slots.includes(v.time)}>{initial.id?'Salvar remarcação':'Confirmar agendamento'}</button></form>;}
function TeamForm({data,initial,onSubmit,busy}){const [v,setV]=useState(initial||{name:'',role:'Barbeiro',commission:40,start:'09:00',end:'20:00',days:[1,2,3,4,5,6],services:[],active:true});const toggle=(key,value)=>setV({...v,[key]:v[key].includes(value)?v[key].filter(x=>x!==value):[...v[key],value]});return <form className="crm-form" onSubmit={e=>{e.preventDefault();onSubmit({...v,commission:Number(v.commission)});}}>{[['name','Nome','text'],['role','Função','text'],['commission','Comissão sobre serviços (%)','number'],['start','Início do expediente','time'],['end','Fim do expediente','time']].map(([key,label,type])=><label key={key}>{label}<input type={type} required min={type==='number'?0:undefined} max={type==='number'?100:undefined} step={type==='number'?0.01:undefined} value={v[key]} onChange={e=>setV({...v,[key]:e.target.value})}/></label>)}<fieldset><legend>Dias de trabalho (studio fechado aos domingos)</legend><div className="crm-checks">{['Seg','Ter','Qua','Qui','Sex','Sáb'].map((d,i)=><label key={d}><input type="checkbox" checked={v.days.includes(i+1)} onChange={()=>toggle('days',i+1)}/>{d}</label>)}</div></fieldset><fieldset><legend>Serviços realizados</legend><div className="crm-checks">{data.services.map(s=><label key={s.id}><input type="checkbox" checked={v.services.includes(s.id)} onChange={()=>toggle('services',s.id)}/>{s.name}</label>)}</div></fieldset><label className="crm-check"><input type="checkbox" checked={v.active} onChange={e=>setV({...v,active:e.target.checked})}/>Profissional ativo</label><button disabled={busy} className="demo-primary">Salvar profissional</button></form>;}
export default function CrmApp(){
 const [data,setData]=useState(null),[tab,setTab]=useState('Visão geral'),[search,setSearch]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState(''),[modal,setModal]=useState(null),[busy,setBusy]=useState(false),[day,setDay]=useState(today()),[professionalFilter,setProfessionalFilter]=useState(''),[statusFilter,setStatusFilter]=useState(''),[orderId,setOrderId]=useState(null),[clientId,setClientId]=useState(null),[from,setFrom]=useState(today().slice(0,7)+'-01'),[to,setTo]=useState(today());
 async function load(){try{const r=await fetch('/api/crm/state');if(!r.ok)throw new Error('Servidor local indisponível. Inicie npm run dev:crm.');setData(await r.json());setError('');}catch(e){setError(e.message);}}
 useEffect(()=>{document.title='Studio Clean · Gestão da barbearia';load();},[]);
 async function act(type,payload,close=true){if(busy)return false;setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/crm/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,payload,revision:data.revision})});const result=await r.json();if(!r.ok){if(r.status===409)await load();throw new Error(result.error);}setData(result);setNotice(result.audit.at(-1).action+'.');if(close)setModal(null);return true;}catch(e){setError(e.message);return false;}finally{setBusy(false);}}
 const go=t=>{setTab(t);setSearch('');setNotice('');setError('');setOrderId(null);setClientId(null);};
 if(!data)return <main className="crm-loading"><h1>Studio Clean</h1><p>{error||'Abrindo a gestão local…'}</p><button onClick={load}>Tentar novamente</button></main>;
 const person=id=>data.clients.find(x=>x.id===id),prof=id=>data.team.find(x=>x.id===id),product=id=>data.products.find(x=>x.id===id);
 const options=list=>list.map(x=>({value:x.id,label:x.name}));
 const payOptions=['Pix','Dinheiro','Débito','Crédito'].map(x=>({value:x,label:x}));
 const matched=c=>`${c.name} ${c.phone||''}`.toLowerCase().includes(search.toLowerCase());
 const session=data.sessions.find(s=>!s.closedAt),pendingOrders=data.orders.filter(o=>o.status==='Aberto');
 const rows=commissionRows(data),paidOrders=data.orders.filter(o=>o.status==='Pago'&&dateOf(o.paidAt)>=from&&dateOf(o.paidAt)<=to),revenue=paidOrders.reduce((sum,o)=>sum+o.total,0);
 const filteredAppointments=data.appointments.filter(a=>(!day||a.date===day)&&(!professionalFilter||a.professionalId===professionalFilter)&&(!statusFilter||a.status===statusFilter)&&`${person(a.clientId)?.name} ${prof(a.professionalId)?.name}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));
 const order=data.orders.find(o=>o.id===orderId),selectedClient=person(clientId);
 function edit(kind,item){setModal({kind,item});setError('');}
 function openOrder(a){const existing=data.orders.find(o=>o.appointmentId===a.id&&['Aberto','Pago'].includes(o.status));if(existing){setOrderId(existing.id);setTab('Comandas');return;}setModal({kind:'orderFromAppointment',item:a});}
 function exportReport(){const lines=[['Data','Cliente','Profissional','Pagamento','Total (R$)'],...paidOrders.map(o=>[BR(dateOf(o.paidAt)),person(o.clientId)?.name,prof(o.professionalId)?.name,o.method,(o.total/100).toFixed(2).replace('.',',')])];const csv='\uFEFF'+lines.map(row=>row.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(';')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`relatorio-${from}-${to}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 const showClients=()=>data.clients.filter(matched);
 const clientFields=[field('name','Nome'),field('phone','Telefone com DDD','tel'),field('email','E-mail','email',{required:false}),field('birthday','Nascimento','date',{required:false}),field('source','Origem','select',{options:['Recepção','Site','Indicação','Instagram','WhatsApp'].map(x=>({value:x,label:x}))}),field('notes','Preferências e observações','textarea'),field('consent','Cliente autorizou comunicações de relacionamento','checkbox')];
 return <div className="demo crm"><aside className="demo-sidebar"><a href="https://clean-studio-blue.vercel.app/" target="_blank" rel="noreferrer"><img src={siteData.images.logoHorizontal} alt="Studio Clean"/></a><p className="demo-kicker">GESTÃO DA BARBEARIA</p><nav aria-label="Gestão">{tabs.map(([label,Icon])=><button key={label} aria-current={tab===label?'page':undefined} onClick={()=>go(label)}><Icon size={18}/>{label}</button>)}</nav><div className="demo-sidebar-bottom"><span className="demo-dot"/>CRM local · banco neste computador<p>Seu estilo. Seu cuidado.<br/>Sua gestão.</p><a href="https://clean-studio-blue.vercel.app/" target="_blank" rel="noreferrer">Abrir site público <ArrowUpRight size={16}/></a></div></aside><main className="demo-main"><div className="demo-banner"><strong>AMBIENTE LOCAL</strong> · Exemplos editáveis. Sem integração ativa com Trinks, bancos ou mensagens. {session?'Caixa aberto':'Caixa fechado'}</div><header className="demo-heading"><div><p className="demo-kicker">{data.settings.name.toUpperCase()} · BARBER & BEAUTY</p><h1>{tab==='Visão geral'?'Seu negócio. Bem cuidado.':tab}</h1><p>{tab==='Visão geral'?'Da cadeira ao caixa, acompanhe a rotina do studio.':'Organização e atenção em cada detalhe.'}</p></div><button className="demo-primary" onClick={()=>edit('appointment')}><Plus size={17}/> Novo agendamento</button></header>{notice&&<div className="demo-notice" role="status">{notice}</div>}{error&&!modal&&<div className="crm-error" role="alert">{error}</div>}
 {tab==='Visão geral'&&<><Stats items={[["Agenda de hoje",data.appointments.filter(a=>a.date===today()&&!['Cancelado','Faltou'].includes(a.status)).length],['Comandas abertas',pendingOrders.length],['Clientes',data.clients.length]]}/><div className="crm-two"><Panel title="Hoje no studio" action={<button onClick={()=>{go('Agenda');setDay(today())}}>Ver agenda →</button>}>{data.appointments.filter(a=>a.date===today()).sort((a,b)=>a.start-b.start).map(a=><div className="crm-list-row" key={a.id}><div><strong>{a.time} · {person(a.clientId)?.name}</strong><small>{a.serviceName} · {prof(a.professionalId)?.name}</small></div><Status value={a.status}/></div>)}{!data.appointments.some(a=>a.date===today())&&<p className="demo-empty">Sua agenda de hoje está livre.</p>}</Panel><Panel title="Atenção na operação"><div className="crm-list-row"><span>Estoque baixo</span><button onClick={()=>go('Estoque')}>{data.products.filter(p=>p.active&&p.stock<=p.min).length} produtos →</button></div><div className="crm-list-row"><span>Comissões pendentes</span><button onClick={()=>go('Comissões')}>{money(rows.filter(r=>!r.payout).reduce((n,r)=>n+r.amount,0))} →</button></div><div className="crm-list-row"><span>Dinheiro esperado em caixa</span><strong>{session?money(cashExpected(data,session)):'Caixa fechado'}</strong></div><p className="crm-muted">Preços, comissões e estoque iniciais são exemplos. Ajuste-os com a equipe antes do uso operacional.</p></Panel></div></>}
 {tab==='Agenda'&&<Panel title="Agenda por profissional" action={<button onClick={()=>edit('block')}>Bloquear horário</button>}><div className="demo-filters"><input aria-label="Buscar na agenda" placeholder="Cliente ou profissional" value={search} onChange={e=>setSearch(e.target.value)}/><input type="date" aria-label="Dia da agenda" value={day} onChange={e=>setDay(e.target.value)}/><select aria-label="Profissional da agenda" value={professionalFilter} onChange={e=>setProfessionalFilter(e.target.value)}><option value="">Todos os profissionais</option>{data.team.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select aria-label="Situação da agenda" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Todas as situações</option>{statusOptions.map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>{setDay('');setSearch('');setProfessionalFilter('');setStatusFilter('')}}>Ver todos</button></div><Table headers={['Horário','Cliente / serviço','Profissional','Situação','Ações']} empty={!filteredAppointments.length}>{filteredAppointments.map(a=><tr key={a.id}><td><strong>{a.time}</strong><small>{BR(a.date)}</small></td><td>{person(a.clientId)?.name}<small>{a.serviceName} · {a.duration} min</small></td><td>{prof(a.professionalId)?.name}</td><td><select aria-label={`Situação de ${person(a.clientId)?.name}`} value={a.status} disabled={busy} onChange={e=>act('appointment.status',{id:a.id,status:e.target.value})}>{statusOptions.map(s=><option key={s}>{s}</option>)}</select></td><td><div className="crm-actions"><button onClick={()=>edit('appointment',a)}>Remarcar</button>{!['Cancelado','Faltou'].includes(a.status)&&<button onClick={()=>openOrder(a)}>Comanda</button>}</div></td></tr>)}</Table><h3 className="crm-subtitle">Bloqueios de agenda</h3>{data.blocks.filter(b=>!day||b.date===day).map(b=><div key={b.id} className="crm-list-row"><span>{BR(b.date)} · {prof(b.professionalId)?.name} · {String(Math.floor(b.start/60)).padStart(2,'0')}:{String(b.start%60).padStart(2,'0')}–{String(Math.floor(b.end/60)).padStart(2,'0')}:{String(b.end%60).padStart(2,'0')} · {b.reason}</span><button disabled={busy} onClick={()=>act('block.remove',{id:b.id})}>Liberar</button></div>)}</Panel>}
 {tab==='Clientes'&&<Panel title={selectedClient?selectedClient.name:'Cadastro e histórico'} action={<button onClick={()=>selectedClient?setClientId(null):edit('client')}>{selectedClient?'Voltar à lista':'+ Novo cliente'}</button>}>{selectedClient?<><div className="crm-detail"><p>{selectedClient.phone} · {selectedClient.email||'Sem e-mail'}<br/>Nascimento: {BR(selectedClient.birthday)} · Origem: {selectedClient.source}</p><p>{selectedClient.notes||'Sem observações.'}</p><button onClick={()=>edit('client',selectedClient)}>Editar cadastro</button></div><Stats items={[["Atendimentos concluídos",data.appointments.filter(a=>a.clientId===clientId&&a.status==='Concluído').length],['Total em comandas pagas',money(data.orders.filter(o=>o.clientId===clientId&&o.status==='Pago').reduce((n,o)=>n+o.total,0))],['Autorização de contato',selectedClient.consent?'Sim':'Não'] ]}/><Table headers={['Dia','Serviço','Profissional','Situação']} empty={!data.appointments.some(a=>a.clientId===clientId)}>{data.appointments.filter(a=>a.clientId===clientId).sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time)).map(a=><tr key={a.id}><td>{BR(a.date)} · {a.time}</td><td>{a.serviceName}</td><td>{prof(a.professionalId)?.name}</td><td><Status value={a.status}/></td></tr>)}</Table></>:<><input className="demo-search" aria-label="Buscar cliente" placeholder="Buscar nome ou telefone" value={search} onChange={e=>setSearch(e.target.value)}/><Table headers={['Cliente','Contato','Origem','Ações']} empty={!showClients().length}>{showClients().map(c=><tr key={c.id}><td><strong>{c.name}</strong><small>{c.notes}</small></td><td>{c.phone}</td><td>{c.source}</td><td><div className="crm-actions"><button onClick={()=>setClientId(c.id)}>Ver ficha</button><button onClick={()=>edit('client',c)}>Editar</button></div></td></tr>)}</Table></>}</Panel>}
 {tab==='Serviços'&&<Panel title="Catálogo de serviços" action={<button onClick={()=>edit('service')}>+ Novo serviço</button>}><Table headers={['Serviço','Duração','Preço','Situação','Ações']}>{data.services.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.duration} min</td><td>{money(s.price)}</td><td>{s.active?'Ativo':'Inativo'}</td><td><button onClick={()=>edit('service',s)}>Editar</button></td></tr>)}</Table><p className="crm-muted">Após cadastrar um serviço, habilite os profissionais que o realizam em Equipe. Mudanças de preço não alteram comandas e reservas já registradas.</p></Panel>}
 {tab==='Equipe'&&<Panel title="Profissionais e expedientes" action={<button onClick={()=>edit('team')}>+ Novo profissional</button>}><div className="demo-clients">{data.team.map(p=><article key={p.id}><div className="demo-avatar">{p.name[0]}</div><h3>{p.name}</h3><p>{p.role} · {p.active?'Ativo':'Inativo'}<br/>{p.start} às {p.end} · Comissão: {p.commission}%</p><small>{p.days.map(d=>['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'][d]).join(' · ')}</small><p>{p.services.map(id=>data.services.find(s=>s.id===id)?.name).join(', ')||'Sem serviços habilitados'}</p><button onClick={()=>edit('team',p)}>Editar profissional</button></article>)}</div><p className="crm-muted">O expediente respeita o fechamento do studio: 20h nos dias úteis e 19h aos sábados. Mudanças no expediente não cancelam reservas existentes.</p></Panel>}
 {tab==='Comandas'&&<Panel title={order?`Comanda · ${person(order.clientId)?.name}`:'Atendimentos e vendas'} action={<button onClick={()=>order?setOrderId(null):edit('order')}>{order?'Voltar à lista':'+ Abrir comanda'}</button>}>{order?<><div className="crm-detail"><span>{prof(order.professionalId)?.name} · {BR(dateOf(order.createdAt))}</span><Status value={order.status}/></div><Table headers={['Item','Quantidade','Unitário','Subtotal','Ação']} empty={!order.items.length}>{order.items.map(i=><tr key={i.id}><td>{i.name}<small>{i.kind==='service'?'Serviço':'Produto'}</small></td><td>{i.quantity}</td><td>{money(i.price)}</td><td>{money(i.price*i.quantity)}</td><td>{order.status==='Aberto'&&<button disabled={busy} onClick={()=>act('order.remove',{id:order.id,itemId:i.id},false)}>Remover</button>}</td></tr>)}</Table><div className="crm-total"><p>Subtotal: {money(orderTotals(order).subtotal)}<br/>Desconto: {money(order.discount)}</p><strong>Total {money(orderTotals(order).total)}</strong></div><div className="crm-actions">{order.status==='Aberto'?<><button onClick={()=>edit('item',order)}>+ Adicionar item</button><button className="demo-primary" disabled={!order.items.length} onClick={()=>edit('payment',order)}>Receber e concluir</button><button onClick={()=>edit('cancelOrder',order)}>Cancelar comanda</button></>:order.status==='Pago'?<><span>Recebido por {order.method} em {BR(dateOf(order.paidAt))}</span><button onClick={()=>edit('refund',order)}>Estornar</button></>:null}</div></>:<><div className="demo-filters"><input placeholder="Buscar cliente" aria-label="Buscar comanda" value={search} onChange={e=>setSearch(e.target.value)}/></div><Table headers={['Cliente','Abertura','Profissional','Total','Situação','Ação']} empty={!data.orders.length}>{data.orders.filter(o=>person(o.clientId)?.name.toLowerCase().includes(search.toLowerCase())).slice().reverse().map(o=><tr key={o.id}><td>{person(o.clientId)?.name}</td><td>{BR(dateOf(o.createdAt))}</td><td>{prof(o.professionalId)?.name}</td><td>{money(orderTotals(o).total)}</td><td><Status value={o.status}/></td><td><button onClick={()=>setOrderId(o.id)}>Abrir</button></td></tr>)}</Table></>}</Panel>}
 {tab==='Caixa'&&<><Stats items={[["Situação",session?'Aberto':'Fechado'],['Fundo inicial',money(session?.opening)],['Dinheiro esperado',money(session?cashExpected(data,session):0)]]}/><Panel title="Movimentação do caixa" action={<div className="crm-actions">{session?<><button onClick={()=>edit('cashMove')}>+ Lançamento</button><button onClick={()=>edit('cashClose')}>Fechar caixa</button></>:<button onClick={()=>edit('cashOpen')}>Abrir caixa</button>}</div>}><p className="crm-muted">Valores registrados no sistema não movimentam bancos. O saldo esperado considera apenas dinheiro; Pix e cartões aparecem separadamente.</p>{session&&<div className="crm-payment-summary">{payOptions.map(({value})=><span key={value}>{value}: <strong>{money(data.movements.filter(m=>m.sessionId===session.id&&m.method===value).reduce((n,m)=>n+m.amount,0))}</strong></span>)}</div>}<Table headers={['Data','Tipo','Descrição','Forma','Valor']} empty={!data.movements.length}>{data.movements.slice().reverse().slice(0,100).map(m=><tr key={m.id}><td>{BR(dateOf(m.at))}</td><td>{m.kind}</td><td>{m.description}</td><td>{m.method}</td><td>{money(m.amount)}</td></tr>)}</Table><h3 className="crm-subtitle">Conferência dos fechamentos</h3><Table headers={['Abertura','Fechamento','Esperado','Contado','Diferença']} empty={!data.sessions.some(s=>s.closedAt)}>{data.sessions.filter(s=>s.closedAt).slice().reverse().map(s=><tr key={s.id}><td>{BR(dateOf(s.openedAt))}</td><td>{BR(dateOf(s.closedAt))}</td><td>{money(s.expected)}</td><td>{money(s.counted)}</td><td>{money(s.difference)}</td></tr>)}</Table></Panel></>}
 {tab==='Estoque'&&<Panel title="Produtos e movimentações" action={<button onClick={()=>edit('product')}>+ Novo produto</button>}><Table headers={['Produto','Venda / custo','Saldo / mínimo','Situação','Ações']}>{data.products.map(p=><tr key={p.id}><td>{p.name}</td><td>{money(p.price)}<small>Custo: {money(p.cost)}</small></td><td>{p.stock} / {p.min}</td><td><Status value={!p.active?'Inativo':p.stock<=p.min?'Estoque baixo':'Disponível'}/></td><td><div className="crm-actions"><button onClick={()=>edit('product',p)}>Editar</button><button onClick={()=>edit('stock',p)}>Movimentar</button></div></td></tr>)}</Table><h3 className="crm-subtitle">Histórico de estoque</h3><Table headers={['Data','Produto','Quantidade','Motivo']} empty={!data.stockMovements.length}>{data.stockMovements.slice().reverse().slice(0,50).map(m=><tr key={m.id}><td>{BR(dateOf(m.at))}</td><td>{product(m.productId)?.name}</td><td>{m.quantity>0?'+':''}{m.quantity}</td><td>{m.reason}</td></tr>)}</Table><p className="crm-muted">Vendas baixam estoque somente ao receber a comanda. Entradas de mercadoria não lançam despesas automaticamente; registre o pagamento no caixa quando necessário.</p></Panel>}
 {tab==='Comissões'&&<Panel title="Produção e repasses"><p className="crm-muted">Comissão sobre serviços pagos, com desconto proporcional. Produtos não geram comissão. A taxa é registrada no recebimento e preservada no histórico.</p><Table headers={['Profissional','Pendente','Já repassado','Ação']}>{data.team.map(p=><tr key={p.id}><td>{p.name}</td><td>{money(rows.filter(r=>r.professionalId===p.id&&!r.payout).reduce((n,r)=>n+r.amount,0))}</td><td>{money(data.payouts.filter(r=>r.professionalId===p.id).reduce((n,r)=>n+r.amount,0))}</td><td><button disabled={!rows.some(r=>r.professionalId===p.id&&!r.payout&&r.amount>0)} onClick={()=>edit('commission',p)}>Registrar repasse</button></td></tr>)}</Table><h3 className="crm-subtitle">Histórico de repasses</h3><Table headers={['Data','Profissional','Valor','Forma']} empty={!data.payouts.length}>{data.payouts.slice().reverse().map(p=><tr key={p.id}><td>{BR(dateOf(p.at))}</td><td>{prof(p.professionalId)?.name}</td><td>{money(p.amount)}</td><td>{p.method}</td></tr>)}</Table></Panel>}
 {tab==='Relacionamento'&&<Panel title="Retorno e acompanhamento"><p className="crm-muted">Clientes sem retorno há {data.settings.returnDays} dias ou aniversariantes do mês. Contatos são manuais; nenhuma mensagem é enviada automaticamente.</p><div className="demo-clients">{data.clients.map(c=>{const last=data.appointments.filter(a=>a.clientId===c.id&&a.status==='Concluído').sort((a,b)=>b.date.localeCompare(a.date))[0];const days=last?Math.floor((new Date(today()+'T12:00:00')-new Date(last.date+'T12:00:00'))/86400000):null;const birthday=c.birthday?.slice(5,7)===today().slice(5,7);return {c,last,days,birthday};}).filter(x=>x.days===null||x.days>=data.settings.returnDays||x.birthday).map(({c,last,days,birthday})=><article key={c.id}><h3>{c.name}</h3><p>{birthday?'Aniversariante do mês · ':''}{last?`${days} dias desde o último atendimento`:'Sem atendimento concluído'}</p><small>{c.consent?'Contato autorizado pelo cliente':'Sem autorização de relacionamento registrada'}</small><div className="crm-actions">{c.consent&&<button onClick={()=>edit('message',c)}>Preparar mensagem</button>}<button onClick={()=>edit('contact',c)}>Registrar contato</button></div>{data.contacts.filter(x=>x.clientId===c.id).slice(-3).reverse().map(x=><p className="demo-history" key={x.id}>{BR(dateOf(x.at))} · {x.note}</p>)}</article>)}</div></Panel>}
 {tab==='Relatórios'&&<><div className="demo-filters"><label>De <input type="date" aria-label="Início do relatório" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Até <input type="date" aria-label="Fim do relatório" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={exportReport}><Download size={16}/> Exportar CSV</button></div>{from>to&&<p className="crm-error">A data inicial deve ser anterior à final.</p>}<Stats items={[["Receita de comandas pagas",money(revenue)],['Ticket médio',money(paidOrders.length?Math.round(revenue/paidOrders.length):0)],['Comandas pagas',paidOrders.length]]}/><Panel title="Resultado por profissional"><Table headers={['Profissional','Comandas','Receita','Comissão gerada']}>{data.team.map(p=>{const orders=paidOrders.filter(o=>o.professionalId===p.id);return <tr key={p.id}><td>{p.name}</td><td>{orders.length}</td><td>{money(orders.reduce((n,o)=>n+o.total,0))}</td><td>{money(orders.reduce((n,o)=>n+o.commissions.reduce((sum,c)=>sum+c.amount,0),0))}</td></tr>;})}</Table><h3 className="crm-subtitle">Agenda no período</h3><div className="crm-payment-summary">{statusOptions.map(status=><span key={status}>{status}: <strong>{data.appointments.filter(a=>a.date>=from&&a.date<=to&&a.status===status).length}</strong></span>)}</div><p className="crm-muted">Receita por data de pagamento, excluindo comandas estornadas. Este relatório não representa lucro nem documento fiscal.</p></Panel></>}
 {tab==='Configurações'&&<div className="crm-two"><Panel title="Preferências do studio"><Form key={data.settings.name+data.settings.returnDays} initial={data.settings} busy={busy} fields={[field('name','Nome do studio'),field('returnDays','Dias para sugerir retorno','number',{min:1,max:365})]} onSubmit={v=>act('settings.save',{...v,returnDays:Number(v.returnDays)})}/></Panel><Panel title="Dados e publicação"><p>Banco local salvo neste computador. O site público permanece separado, no domínio atual.</p><p className="crm-muted">O novo domínio do CRM será configurado em uma hospedagem própria com servidor, autenticação e permissões. Não há conexão ativa com Trinks, Google ou WhatsApp automático.</p><a className="demo-primary" href="/api/crm/backup" download><Download size={17}/> Baixar cópia dos dados</a><small>O arquivo contém cadastros e lançamentos. Guarde em local privado. Restauração requer suporte técnico nesta versão.</small></Panel><Panel title="Histórico de alterações"><div className="crm-audit">{data.audit.slice(-30).reverse().map(a=><div key={a.id} className="crm-list-row"><small>{new Date(a.at).toLocaleString('pt-BR')}</small><span>{a.action}</span></div>)}</div></Panel></div>}
 </main>
 {modal&&<Modal title={{client:modal.item?'Editar cliente':'Novo cliente',appointment:modal.item?'Remarcar atendimento':'Novo agendamento',service:'Serviço',team:'Profissional',block:'Bloquear horário',order:'Abrir comanda',orderFromAppointment:'Iniciar atendimento',item:'Adicionar item',payment:'Receber comanda',refund:'Estornar comanda',cancelOrder:'Cancelar comanda',cashOpen:'Abrir caixa',cashMove:'Lançamento de caixa',cashClose:'Conferir e fechar caixa',product:'Produto',stock:'Movimentação de estoque',commission:'Registrar repasse',contact:'Registrar contato',message:'Mensagem para revisão'}[modal.kind]} onClose={()=>{if(!busy){setModal(null);setError('')}}}>{error&&<div className="crm-error" role="alert">{error}</div>}
 {modal.kind==='client'&&<Form fields={clientFields} initial={modal.item||{source:'Recepção',consent:false}} busy={busy} onSubmit={v=>act('client.save',v)}/>}
 {modal.kind==='appointment'&&<AppointmentForm data={data} initial={modal.item} busy={busy} onSubmit={v=>act('appointment.save',v)}/>}
 {modal.kind==='service'&&<Form initial={modal.item?{...modal.item,price:modal.item.price/100}:{duration:30,price:0,active:true}} fields={[field('name','Nome do serviço'),field('price','Preço (R$)','number',{min:0,step:0.01}),field('duration','Duração em minutos','number',{min:15,max:480,step:15}),field('active','Serviço ativo','checkbox')]} busy={busy} onSubmit={v=>act('service.save',{...v,price:cents(v.price),duration:Number(v.duration)})}/>}
 {modal.kind==='team'&&<TeamForm data={data} initial={modal.item} busy={busy} onSubmit={v=>act('team.save',v)}/>}
 {modal.kind==='block'&&<Form initial={{date:day||today(),start:'12:00',end:'13:00'}} fields={[field('professionalId','Profissional','select',{options:options(data.team)}),field('date','Dia','date'),field('start','De','time'),field('end','Até','time'),field('reason','Motivo')]} busy={busy} onSubmit={v=>act('block.add',v)}/>}
 {modal.kind==='order'&&<Form fields={[field('clientId','Cliente','select',{options:options(data.clients)}),field('professionalId','Profissional','select',{options:options(data.team.filter(p=>p.active))})]} busy={busy} onSubmit={v=>act('order.create',v)}/>}
 {modal.kind==='orderFromAppointment'&&<><p>{person(modal.item.clientId)?.name} · {modal.item.serviceName} · {money(modal.item.price)}</p><p className="crm-muted">Abrir uma comanda inclui este serviço e marca o atendimento como em andamento.</p><button disabled={busy} className="demo-primary" onClick={async()=>{if(await act('order.create',{clientId:modal.item.clientId,professionalId:modal.item.professionalId,appointmentId:modal.item.id}))setTab('Comandas')}}>Abrir comanda do atendimento</button></>}
 {modal.kind==='item'&&<Form initial={{quantity:1}} fields={[field('item','Serviço ou produto','select',{options:[...data.services.filter(s=>s.active&&prof(modal.item.professionalId)?.services.includes(s.id)).map(s=>({value:'service:'+s.id,label:`Serviço · ${s.name} · ${money(s.price)}`})),...data.products.filter(p=>p.active).map(p=>({value:'product:'+p.id,label:`Produto · ${p.name} · ${money(p.price)} (${p.stock} un.)`}))]}),field('quantity','Quantidade','number',{min:1,step:1})]} busy={busy} onSubmit={v=>{const [kind,referenceId]=v.item.split(':');act('order.item',{id:modal.item.id,kind,referenceId,quantity:Number(v.quantity)})}}/>}
 {modal.kind==='payment'&&<><p>Subtotal: <strong>{money(orderTotals(modal.item).subtotal)}</strong></p><Form initial={{discount:0,method:'Pix'}} fields={[field('discount','Desconto (R$)','number',{min:0,max:orderTotals(modal.item).subtotal/100,step:0.01}),field('method','Forma de pagamento','select',{options:payOptions})]} submit="Registrar recebimento" busy={busy} onSubmit={v=>act('order.pay',{id:modal.item.id,discount:cents(v.discount),method:v.method})}/></>}
 {modal.kind==='refund'&&<><p>O estorno reverte o recebimento e devolve produtos ao estoque. Não realiza devolução bancária.</p><Form fields={[field('reason','Motivo do estorno')]} submit="Registrar estorno" busy={busy} onSubmit={v=>act('order.refund',{id:modal.item.id,...v})}/></>}
 {modal.kind==='cancelOrder'&&<><p>Cancelar esta comanda aberta? Nenhum pagamento será registrado.</p><button disabled={busy} className="demo-primary" onClick={()=>act('order.cancel',{id:modal.item.id})}>Confirmar cancelamento</button></>}
 {modal.kind==='cashOpen'&&<Form initial={{opening:0}} fields={[field('opening','Fundo inicial em dinheiro (R$)','number',{min:0,step:0.01})]} busy={busy} onSubmit={v=>act('cash.open',{opening:cents(v.opening)})}/>}
 {modal.kind==='cashMove'&&<Form initial={{method:'Dinheiro',kind:'Despesa'}} fields={[field('kind','Tipo','select',{options:['Despesa','Sangria','Suprimento'].map(x=>({value:x,label:x}))}),field('amount','Valor (R$)','number',{min:0.01,step:0.01}),field('method','Forma','select',{options:payOptions}),field('description','Descrição')]} busy={busy} onSubmit={v=>act('cash.move',{...v,amount:cents(v.amount)})}/>}
 {modal.kind==='cashClose'&&<><p>Dinheiro esperado: <strong>{money(cashExpected(data,session))}</strong></p><Form fields={[field('counted','Dinheiro contado (R$)','number',{min:0,step:0.01})]} busy={busy} submit="Fechar e registrar diferença" onSubmit={v=>act('cash.close',{counted:cents(v.counted)})}/></>}
 {modal.kind==='product'&&<Form initial={modal.item?{...modal.item,price:modal.item.price/100,cost:modal.item.cost/100}:{price:0,cost:0,min:3,active:true}} fields={[field('name','Nome do produto'),field('price','Preço de venda (R$)','number',{min:0,step:0.01}),field('cost','Custo unitário (R$)','number',{min:0,step:0.01}),field('min','Estoque mínimo','number',{min:0,step:1}),field('active','Produto ativo','checkbox')]} busy={busy} onSubmit={v=>act('product.save',{...v,price:cents(v.price),cost:cents(v.cost),min:Number(v.min)})}/>}
 {modal.kind==='stock'&&<><p>{modal.item.name} · Saldo: {modal.item.stock}</p><Form fields={[field('quantity','Quantidade (positiva para entrada, negativa para saída)','number',{step:1}),field('reason','Motivo da movimentação')]} busy={busy} onSubmit={v=>act('stock.move',{id:modal.item.id,quantity:Number(v.quantity),reason:v.reason})}/></>}
 {modal.kind==='commission'&&<><p>{modal.item.name} · Pendente: <strong>{money(rows.filter(r=>r.professionalId===modal.item.id&&!r.payout).reduce((n,r)=>n+r.amount,0))}</strong></p><p className="crm-muted">Registro interno do repasse. Nenhuma transferência bancária será realizada.</p><Form initial={{method:'Pix'}} fields={[field('method','Forma','select',{options:payOptions.filter(o=>['Pix','Dinheiro'].includes(o.value))})]} busy={busy} onSubmit={v=>act('commission.pay',{professionalId:modal.item.id,method:v.method})}/></>}
 {modal.kind==='contact'&&<Form fields={[field('note','Resumo do contato','textarea')]} busy={busy} onSubmit={v=>act('contact.add',{clientId:modal.item.id,note:v.note})}/>}
 {modal.kind==='message'&&<><p className="crm-message">Olá, {modal.item.name}! Tudo bem? Aqui é do {data.settings.name}. Quer reservar seu próximo horário de cuidado? Podemos ajudar a escolher o melhor dia para você.</p><p className="crm-muted">Copie e revise a mensagem antes de enviar manualmente. Nenhum envio é feito por este CRM.</p><button className="demo-primary" onClick={async()=>{try{await navigator.clipboard.writeText(`Olá, ${modal.item.name}! Tudo bem? Aqui é do ${data.settings.name}. Quer reservar seu próximo horário de cuidado? Podemos ajudar a escolher o melhor dia para você.`);setNotice('Mensagem copiada para revisão.');setModal(null);}catch{setError('Não foi possível copiar. Selecione e copie o texto acima.')}}}>Copiar mensagem</button></>}
 </Modal>}
 </div>;
}
