export const today = () => {const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
export const money = cents => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((cents||0)/100);
export const minutes = time => Number(time.slice(0,2))*60+Number(time.slice(3));
export const statusOptions=['Confirmado','Chegou','Em atendimento','Concluído','Faltou','Cancelado'];
export function initialState(){
 const date=today();
 return {version:1,revision:0,settings:{name:'Studio Clean',returnDays:30},clients:[{id:'c1',name:'Cliente exemplo',phone:'61999990000',email:'',birthday:'',notes:'Cadastro fictício para apresentação.',source:'Site',consent:false}],services:[{id:'s1',name:'Corte masculino',price:5000,duration:30,active:true},{id:'s2',name:'Barba',price:3500,duration:30,active:true},{id:'s3',name:'Cabelo e barba',price:8000,duration:60,active:true},{id:'s4',name:'Podologia',price:12000,duration:60,active:true}],team:[{id:'p1',name:'Gustavo',role:'Barbeiro',commission:40,services:['s1','s2','s3'],start:'09:00',end:'20:00',days:[1,2,3,4,5,6],active:true},{id:'p2',name:'Matheus',role:'Barbeiro',commission:40,services:['s1','s2','s3'],start:'09:00',end:'20:00',days:[1,2,3,4,5,6],active:true},{id:'p3',name:'Alan',role:'Barbeiro',commission:40,services:['s1','s2','s3'],start:'09:00',end:'20:00',days:[1,2,3,4,5,6],active:true},{id:'p4',name:'Edilene',role:'Podóloga',commission:40,services:['s4'],start:'09:00',end:'19:00',days:[1,2,3,4,5,6],active:true}],products:[{id:'pr1',name:'Pomada modeladora · exemplo',price:4500,cost:2000,stock:12,min:3,active:true},{id:'pr2',name:'Óleo para barba · exemplo',price:3500,cost:1500,stock:8,min:3,active:true}],appointments:[],blocks:[],orders:[],sessions:[],movements:[],stockMovements:[],payouts:[],contacts:[],audit:[{id:'initial',at:new Date().toISOString(),action:'Base local criada com exemplos editáveis',date}]};
}
const fail=message=>{throw new Error(message)};
const required=(s,label)=>typeof s==='string'&&s.trim()?s.trim():fail(`Informe ${label}.`);
const integer=(v,label,min=0)=>Number.isSafeInteger(v)&&v>=min?v:fail(`${label}: valor inválido.`);
const get=(list,id,label)=>list.find(x=>x.id===id)||fail(`${label} não encontrado.`);
const validDate=d=>/^\d{4}-\d{2}-\d{2}$/.test(d||'')&&!Number.isNaN(new Date(d+'T12:00:00').getTime())&&new Date(d+'T12:00:00').toISOString().slice(0,10)===d;
const validTime=t=>/^([01]\d|2[0-3]):[0-5]\d$/.test(t||'');
const activeSession=s=>s.sessions.find(x=>!x.closedAt);
export function available(s,{date,professionalId,serviceId,excludeId},now=new Date()){
 const p=s.team.find(x=>x.id===professionalId&&x.active),service=s.services.find(x=>x.id===serviceId&&x.active);
 if(!p||!service||!validDate(date)||!p.services.includes(serviceId)||new Date(date+'T12:00:00').getDay()===0||!p.days.includes(new Date(date+'T12:00:00').getDay()))return [];
 const closing=Math.min(minutes(p.end),new Date(date+'T12:00:00').getDay()===6?1140:1200),result=[];
 for(let start=Math.max(540,minutes(p.start));start+service.duration<=closing;start+=15){const time=`${String(Math.floor(start/60)).padStart(2,'0')}:${String(start%60).padStart(2,'0')}`;if(new Date(`${date}T${time}:00`)<=now)continue;
 const conflict=s.appointments.some(a=>a.id!==excludeId&&a.professionalId===p.id&&a.date===date&&!['Cancelado','Faltou'].includes(a.status)&&start<a.start+a.duration&&start+service.duration>a.start)||s.blocks.some(a=>a.professionalId===p.id&&a.date===date&&start<a.end&&start+service.duration>a.start);
 if(!conflict)result.push(time);
 }return result;
}
export function orderTotals(order){const subtotal=order.items.reduce((sum,i)=>sum+i.price*i.quantity,0);return {subtotal,total:subtotal-order.discount};}
export function cashExpected(s,session){return session.opening+s.movements.filter(m=>m.sessionId===session.id&&m.method==='Dinheiro').reduce((sum,m)=>sum+m.amount,0);}
export function commissionRows(s){return s.orders.filter(o=>o.status==='Pago').flatMap(o=>o.commissions.map(c=>({...c,orderId:o.id,paidAt:o.paidAt,payout:s.payouts.find(p=>p.orderIds.includes(o.id)&&p.professionalId===c.professionalId)})));}
export function applyAction(previous,action,uid,now=new Date()){
 const s=structuredClone(previous),{type,payload:p={}}=action,stamp=now.toISOString(),id=()=>uid();let description=type;
 switch(type){
 case 'client.save': {const name=required(p.name,'o nome'),phone=String(p.phone||'').replace(/\D/g,'');if(!/^\d{10,11}$/.test(phone))fail('Telefone deve ter DDD e 10 ou 11 dígitos.');if(s.clients.some(c=>c.id!==p.id&&c.phone===phone))fail('Já existe um cliente com este telefone.');if(p.birthday&&!validDate(p.birthday))fail('Data de nascimento inválida.');const c={id:p.id||id(),name,phone,email:String(p.email||''),birthday:p.birthday||'',notes:String(p.notes||''),source:p.source||'Recepção',consent:!!p.consent};if(p.id){get(s.clients,p.id,'Cliente');s.clients=s.clients.map(x=>x.id===p.id?c:x);}else s.clients.push(c);description='Cadastro de cliente atualizado';break;}
 case 'service.save':{const item={id:p.id||id(),name:required(p.name,'o serviço'),price:integer(p.price,'Preço'),duration:integer(p.duration,'Duração',15),active:p.active!==false};if(item.duration>480||item.duration%15)fail('Duração deve ser múltipla de 15 minutos, até 480.');if(p.id){get(s.services,p.id,'Serviço');s.services=s.services.map(x=>x.id===p.id?item:x);}else s.services.push(item);description='Serviço atualizado';break;}
 case 'team.save':{if(!validTime(p.start)||!validTime(p.end)||minutes(p.start)>=minutes(p.end))fail('Confira o início e o fim do expediente.');if(!Number.isFinite(p.commission)||p.commission<0||p.commission>100)fail('Comissão deve ficar entre 0 e 100%.');if(!Array.isArray(p.days)||p.days.some(d=>!Number.isInteger(d)||d<0||d>6)||!Array.isArray(p.services))fail('Selecione dias e serviços válidos.');p.services.forEach(sid=>get(s.services,sid,'Serviço'));const item={id:p.id||id(),name:required(p.name,'o profissional'),role:required(p.role,'a função'),commission:p.commission,start:p.start,end:p.end,days:p.days,services:p.services,active:p.active!==false};if(p.id){get(s.team,p.id,'Profissional');s.team=s.team.map(x=>x.id===p.id?item:x);}else s.team.push(item);description='Profissional atualizado';break;}
 case 'appointment.save':{get(s.clients,p.clientId,'Cliente');const service=get(s.services,p.serviceId,'Serviço');if(!available(s,{...p,excludeId:p.id},now).includes(p.time))fail('Horário indisponível. Confira expediente, bloqueios e conflitos.');const old=p.id?get(s.appointments,p.id,'Agendamento'):null;if(old&&s.orders.some(o=>o.appointmentId===p.id&&!['Estornado','Cancelado'].includes(o.status)))fail('Agendamento com comanda não pode ser remarcado.');const a={id:p.id||id(),clientId:p.clientId,serviceId:p.serviceId,serviceName:service.name,price:service.price,professionalId:p.professionalId,date:p.date,time:p.time,start:minutes(p.time),duration:service.duration,status:'Confirmado',notes:String(p.notes||'')};if(old)s.appointments=s.appointments.map(x=>x.id===p.id?a:x);else s.appointments.push(a);description=old?'Agendamento remarcado':'Agendamento criado';break;}
 case 'appointment.status':{const a=get(s.appointments,p.id,'Agendamento');if(!statusOptions.includes(p.status))fail('Situação inválida.');if(s.orders.some(o=>o.appointmentId===a.id&&o.status==='Pago'))fail('Atendimento pago: estorne a comanda antes de alterar.');if(['Cancelado','Faltou'].includes(p.status)&&s.orders.some(o=>o.appointmentId===a.id&&o.status==='Aberto'))fail('Cancele a comanda aberta primeiro.');if(['Cancelado','Faltou'].includes(a.status)&&!['Cancelado','Faltou'].includes(p.status))fail('Use Remarcar para reativar este agendamento.');a.status=p.status;description='Situação do atendimento alterada';break;}
 case 'block.add':{get(s.team,p.professionalId,'Profissional');if(!validDate(p.date)||!validTime(p.start)||!validTime(p.end)||minutes(p.end)<=minutes(p.start))fail('Informe data e intervalo válidos.');const start=minutes(p.start),end=minutes(p.end);if(s.appointments.some(a=>a.date===p.date&&a.professionalId===p.professionalId&&!['Cancelado','Faltou'].includes(a.status)&&start<a.start+a.duration&&end>a.start))fail('Há atendimento neste intervalo. Remarque antes de bloquear.');s.blocks.push({id:id(),professionalId:p.professionalId,date:p.date,start,end,reason:required(p.reason,'o motivo')});description='Horário bloqueado';break;}
 case 'block.remove':get(s.blocks,p.id,'Bloqueio');s.blocks=s.blocks.filter(b=>b.id!==p.id);description='Bloqueio removido';break;
 case 'order.create':{get(s.clients,p.clientId,'Cliente');const professional=get(s.team,p.professionalId,'Profissional');if(!professional.active)fail('Profissional inativo.');const items=[];if(p.appointmentId){const a=get(s.appointments,p.appointmentId,'Agendamento');if(a.clientId!==p.clientId||a.professionalId!==p.professionalId||['Cancelado','Faltou'].includes(a.status))fail('Agendamento incompatível com a comanda.');if(s.orders.some(o=>o.appointmentId===a.id&&o.status!=='Estornado'&&o.status!=='Cancelado'))fail('Este agendamento já possui comanda.');items.push({id:id(),kind:'service',referenceId:a.serviceId,name:a.serviceName,price:a.price,quantity:1});a.status='Em atendimento';}s.orders.push({id:id(),clientId:p.clientId,professionalId:p.professionalId,appointmentId:p.appointmentId||null,createdAt:stamp,status:'Aberto',items,discount:0,commissions:[]});description='Comanda aberta';break;}
 case 'order.item':{const o=get(s.orders,p.id,'Comanda');if(o.status!=='Aberto')fail('Comanda encerrada.');if(!['service','product'].includes(p.kind))fail('Tipo de item inválido.');const item=get(p.kind==='service'?s.services:s.products,p.referenceId,'Item');if(!item.active)fail('Item inativo.');if(p.kind==='service'&&!get(s.team,o.professionalId,'Profissional').services.includes(item.id))fail('Este profissional não realiza o serviço selecionado.');const quantity=integer(p.quantity,'Quantidade',1);o.items.push({id:id(),kind:p.kind,referenceId:item.id,name:item.name,price:item.price,quantity});description='Item adicionado à comanda';break;}
 case 'order.remove':{const o=get(s.orders,p.id,'Comanda');if(o.status!=='Aberto')fail('Comanda encerrada.');get(o.items,p.itemId,'Item');o.items=o.items.filter(x=>x.id!==p.itemId);o.discount=Math.min(o.discount,orderTotals({...o,discount:0}).subtotal);description='Item removido da comanda';break;}
 case 'order.cancel':{const o=get(s.orders,p.id,'Comanda');if(o.status!=='Aberto')fail('Somente comandas abertas podem ser canceladas.');o.status='Cancelado';if(o.appointmentId)get(s.appointments,o.appointmentId,'Agendamento').status='Confirmado';description='Comanda cancelada';break;}
 case 'order.pay':{const o=get(s.orders,p.id,'Comanda');if(o.status!=='Aberto'||!o.items.length)fail('Comanda vazia ou já encerrada.');const session=activeSession(s)||fail('Abra o caixa antes de receber.');o.discount=integer(p.discount,'Desconto');const {subtotal,total}=orderTotals(o);if(!Number.isSafeInteger(subtotal)||!Number.isSafeInteger(total))fail('Valor da comanda acima do limite permitido.');if(total<0)fail('Desconto maior que o valor da comanda.');if(!['Pix','Dinheiro','Débito','Crédito'].includes(p.method))fail('Forma de pagamento inválida.');const needed={};for(const item of o.items)if(item.kind==='product')needed[item.referenceId]=(needed[item.referenceId]||0)+item.quantity;for(const [pid,q]of Object.entries(needed)){const product=get(s.products,pid,'Produto');if(product.stock<q)fail(`Estoque insuficiente: ${product.name}.`);product.stock-=q;s.stockMovements.push({id:id(),productId:pid,quantity:-q,reason:'Venda em comanda',orderId:o.id,at:stamp});}const prof=get(s.team,o.professionalId,'Profissional');const serviceTotal=o.items.filter(i=>i.kind==='service').reduce((n,i)=>n+i.price*i.quantity,0);o.commissions=[{professionalId:prof.id,rate:prof.commission,amount:Math.round((subtotal?total*serviceTotal/subtotal:0)*prof.commission/100)}];o.status='Pago';o.paidAt=stamp;o.method=p.method;o.total=total;o.sessionId=session.id;s.movements.push({id:id(),sessionId:session.id,orderId:o.id,amount:total,method:p.method,kind:'Recebimento',description:'Pagamento de comanda',at:stamp});if(o.appointmentId)get(s.appointments,o.appointmentId,'Agendamento').status='Concluído';description='Comanda recebida e estoque atualizado';break;}
 case 'order.refund':{const o=get(s.orders,p.id,'Comanda');if(o.status!=='Pago')fail('Somente comandas pagas podem ser estornadas.');if(s.payouts.some(x=>x.orderIds.includes(o.id)))fail('Comissão já paga. Regularize o repasse antes de estornar; estorno automático indisponível neste caso.');const session=activeSession(s)||fail('Abra o caixa para registrar o estorno.');const reason=required(p.reason,'o motivo do estorno');o.status='Estornado';o.refundedAt=stamp;o.refundReason=reason;for(const item of o.items)if(item.kind==='product'){get(s.products,item.referenceId,'Produto').stock+=item.quantity;s.stockMovements.push({id:id(),productId:item.referenceId,quantity:item.quantity,reason:'Estorno de venda',orderId:o.id,at:stamp});}s.movements.push({id:id(),sessionId:session.id,orderId:o.id,amount:-o.total,method:o.method,kind:'Estorno',description:reason,at:stamp});description='Comanda estornada';break;}
 case 'cash.open':if(activeSession(s))fail('Já existe um caixa aberto.');s.sessions.push({id:id(),openedAt:stamp,opening:integer(p.opening,'Fundo de caixa')});description='Caixa aberto';break;
 case 'cash.move':{const session=activeSession(s)||fail('Abra o caixa primeiro.');if(!['Despesa','Sangria','Suprimento'].includes(p.kind)||!['Dinheiro','Pix','Débito','Crédito'].includes(p.method))fail('Movimentação inválida.');const amount=integer(p.amount,'Valor',1)*(p.kind==='Suprimento'?1:-1);if(p.method==='Dinheiro'&&cashExpected(s,session)+amount<0)fail('Saldo em dinheiro insuficiente.');s.movements.push({id:id(),sessionId:session.id,kind:p.kind,method:p.method,amount,description:required(p.description,'a descrição'),at:stamp});description='Movimentação de caixa registrada';break;}
 case 'cash.close':{const session=activeSession(s)||fail('Não existe caixa aberto.');session.expected=cashExpected(s,session);session.counted=integer(p.counted,'Valor contado');session.difference=session.counted-session.expected;session.closedAt=stamp;description='Caixa fechado e conferido';break;}
 case 'product.save':{const old=p.id?get(s.products,p.id,'Produto'):null;const item={id:old?.id||id(),name:required(p.name,'o produto'),price:integer(p.price,'Preço'),cost:integer(p.cost,'Custo'),min:integer(p.min,'Estoque mínimo'),stock:old?.stock||0,active:p.active!==false};if(old)s.products=s.products.map(x=>x.id===p.id?item:x);else s.products.push(item);description='Produto atualizado';break;}
 case 'stock.move':{const item=get(s.products,p.id,'Produto');if(!Number.isSafeInteger(p.quantity)||!p.quantity||item.stock+p.quantity<0)fail('Quantidade inválida ou saldo insuficiente.');item.stock+=p.quantity;s.stockMovements.push({id:id(),productId:item.id,quantity:p.quantity,reason:required(p.reason,'o motivo'),at:stamp});description='Movimentação de estoque registrada';break;}
 case 'commission.pay':{const session=activeSession(s)||fail('Abra o caixa para registrar o repasse.');get(s.team,p.professionalId,'Profissional');const rows=commissionRows(s).filter(c=>c.professionalId===p.professionalId&&!c.payout);const amount=rows.reduce((n,c)=>n+c.amount,0);if(amount<=0)fail('Nenhuma comissão pendente.');if(!['Pix','Dinheiro'].includes(p.method))fail('Escolha Pix ou Dinheiro.');if(p.method==='Dinheiro'&&cashExpected(s,session)<amount)fail('Saldo em dinheiro insuficiente.');const payout={id:id(),professionalId:p.professionalId,amount,orderIds:rows.map(c=>c.orderId),at:stamp,method:p.method};s.payouts.push(payout);s.movements.push({id:id(),sessionId:session.id,amount:-amount,kind:'Comissão',method:p.method,description:'Repasse de comissão',at:stamp});description='Repasse de comissão registrado';break;}
 case 'contact.add':get(s.clients,p.clientId,'Cliente');s.contacts.push({id:id(),clientId:p.clientId,note:required(p.note,'o registro do contato'),at:stamp});description='Contato registrado';break;
 case 'settings.save':s.settings={name:required(p.name,'o nome da empresa'),returnDays:integer(p.returnDays,'Intervalo de retorno',1)};description='Preferências atualizadas';break;
 default:fail('Operação não reconhecida.');
 }
 s.revision++;s.audit.push({id:id(),at:stamp,action:description});return s;
}
