import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,applyAction,available,orderTotals,cashExpected,commissionRows} from '../src/crm/model.js';
let i=0;const uid=()=>`id-${++i}`,now=new Date('2026-09-30T08:00:00');
const action=(s,type,payload)=>applyAction(s,{type,payload},uid,now);
const booking={clientId:'c1',professionalId:'p1',serviceId:'s1',date:'2026-10-01',time:'10:00'};
function orderBase(){let s=initialState();s=action(s,'cash.open',{opening:10000});s=action(s,'appointment.save',booking);s=action(s,'order.create',{clientId:'c1',professionalId:'p1',appointmentId:s.appointments[0].id});return s;}
test('agenda evita sobreposição e permite outro profissional',()=>{const s=action(initialState(),'appointment.save',booking);const slots=available(s,booking,now);assert(!slots.includes('09:45'));assert(!slots.includes('10:00'));assert(!slots.includes('10:15'));assert(slots.includes('10:30'));assert(available(s,{...booking,professionalId:'p2'},now).includes('10:00'));assert.throws(()=>action(s,'appointment.save',booking),/indisponível/);});
test('domingo, passado, competência e encerramento respeitados',()=>{const s=initialState();assert.equal(available(s,{...booking,date:'2026-10-04'},now).length,0);assert.equal(available(s,{...booking,date:'2026-09-29'},now).length,0);assert.equal(available(s,{...booking,serviceId:'s4'},now).length,0);assert(!available(s,{...booking,date:'2026-10-03',serviceId:'s3'},now).includes('18:15'));});
test('bloqueios impedem reserva e rejeitam conflito com atendimento',()=>{let s=action(initialState(),'block.add',{professionalId:'p1',date:'2026-10-01',start:'10:00',end:'11:00',reason:'Almoço'});assert.throws(()=>action(s,'appointment.save',booking),/indisponível/);s=action(s,'block.remove',{id:s.blocks[0].id});s=action(s,'appointment.save',booking);assert.throws(()=>action(s,'block.add',{professionalId:'p1',date:booking.date,start:'10:15',end:'11:00',reason:'Pausa'}),/atendimento/);});
test('remarcação mantém id, cancelamento libera vaga',()=>{let s=action(initialState(),'appointment.save',booking);const id=s.appointments[0].id;s=action(s,'appointment.save',{...booking,id,time:'11:00'});assert.equal(s.appointments.length,1);assert.equal(s.appointments[0].time,'11:00');s=action(s,'appointment.status',{id,status:'Cancelado'});assert(available(s,booking,now).includes('11:00'));});
test('recebimento atualiza caixa, estoque, comissão e atendimento uma vez',()=>{let s=orderBase();const id=s.orders[0].id;s=action(s,'order.item',{id,kind:'product',referenceId:'pr1',quantity:2});s=action(s,'order.pay',{id,discount:1400,method:'Dinheiro'});assert.equal(s.orders[0].total,12600);assert.equal(s.products[0].stock,10);assert.equal(s.orders[0].commissions[0].amount,1800);assert.equal(s.appointments[0].status,'Concluído');assert.equal(cashExpected(s,s.sessions[0]),22600);assert.throws(()=>action(s,'order.pay',{id,discount:0,method:'Dinheiro'}),/encerrada/);});
test('falha por estoque não altera valores nem baixa parcialmente',()=>{let s=orderBase();const id=s.orders[0].id;s=action(s,'order.item',{id,kind:'product',referenceId:'pr1',quantity:8});s=action(s,'order.item',{id,kind:'product',referenceId:'pr1',quantity:8});const before=structuredClone(s);assert.throws(()=>action(s,'order.pay',{id,discount:0,method:'Pix'}),/Estoque insuficiente/);assert.deepEqual(s,before);});
test('estorno devolve estoque e anula comissão sem duplicação',()=>{let s=orderBase();const id=s.orders[0].id;s=action(s,'order.item',{id,kind:'product',referenceId:'pr1',quantity:1});s=action(s,'order.pay',{id,discount:0,method:'Pix'});s=action(s,'order.refund',{id,reason:'Teste de estorno'});assert.equal(s.products[0].stock,12);assert.equal(commissionRows(s).length,0);assert.equal(s.movements.reduce((n,m)=>n+m.amount,0),0);assert.throws(()=>action(s,'order.refund',{id,reason:'Duplicado'}),/pagas/);});
test('repasse impede pagamento duplicado e protege estorno com comissão paga',()=>{let s=orderBase();const id=s.orders[0].id;s=action(s,'order.pay',{id,discount:0,method:'Pix'});s=action(s,'commission.pay',{professionalId:'p1',method:'Pix'});assert.equal(s.payouts[0].amount,2000);assert.throws(()=>action(s,'commission.pay',{professionalId:'p1',method:'Pix'}),/Nenhuma/);assert.throws(()=>action(s,'order.refund',{id,reason:'Teste'}),/Comissão já paga/);});
test('caixa exige abertura, separa Pix e calcula diferença',()=>{let s=initialState();assert.throws(()=>action(s,'cash.move',{kind:'Sangria',amount:100,method:'Dinheiro',description:'Teste'}),/Abra/);s=action(s,'cash.open',{opening:10000});assert.throws(()=>action(s,'cash.open',{opening:0}),/Já existe/);s=action(s,'cash.move',{kind:'Despesa',amount:500,method:'Pix',description:'Material'});assert.equal(cashExpected(s,s.sessions[0]),10000);assert.throws(()=>action(s,'cash.move',{kind:'Sangria',amount:11000,method:'Dinheiro',description:'Teste'}),/insuficiente/);s=action(s,'cash.close',{counted:9900});assert.equal(s.sessions[0].difference,-100);});
test('cadastros rejeitam telefone duplicado, negativos e duração incompatível',()=>{let s=initialState();assert.throws(()=>action(s,'client.save',{name:'Outro',phone:'61999990000'}),/Já existe/);assert.throws(()=>action(s,'service.save',{name:'Teste',price:-1,duration:30}),/inválido/);assert.throws(()=>action(s,'service.save',{name:'Teste',price:100,duration:20}),/múltipla/);assert.throws(()=>action(s,'stock.move',{id:'pr1',quantity:-13,reason:'Teste'}),/insuficiente/);});
test('comanda duplicada e desconto excessivo são rejeitados',()=>{let s=orderBase();assert.throws(()=>action(s,'order.create',{clientId:'c1',professionalId:'p1',appointmentId:s.appointments[0].id}),/já possui/);assert.throws(()=>action(s,'order.pay',{id:s.orders[0].id,discount:6000,method:'Pix'}),/Desconto maior/);assert.equal(orderTotals(s.orders[0]).total,5000);});

test('cancelar comanda permite remarcar e abrir outra comanda',()=>{let s=orderBase();const appointmentId=s.appointments[0].id;s=action(s,'order.cancel',{id:s.orders[0].id});s=action(s,'appointment.save',{...booking,id:appointmentId,time:'11:00'});s=action(s,'order.create',{clientId:'c1',professionalId:'p1',appointmentId});assert.equal(s.orders[1].status,'Aberto');});
test('mudança de preço e taxa não reescreve recebimentos anteriores',()=>{let s=orderBase();s=action(s,'order.pay',{id:s.orders[0].id,discount:0,method:'Pix'});s=action(s,'service.save',{...s.services[0],price:9000});s=action(s,'team.save',{...s.team[0],commission:60});assert.equal(s.orders[0].total,5000);assert.equal(s.orders[0].commissions[0].amount,2000);});
test('pagamento com caixa fechado e alterações de atendimento pago são rejeitados',()=>{let s=orderBase();const oid=s.orders[0].id;s=action(s,'cash.close',{counted:10000});assert.throws(()=>action(s,'order.pay',{id:oid,discount:0,method:'Pix'}),/Abra o caixa/);s=action(s,'cash.open',{opening:0});s=action(s,'order.pay',{id:oid,discount:0,method:'Pix'});assert.throws(()=>action(s,'appointment.status',{id:s.appointments[0].id,status:'Cancelado'}),/Atendimento pago/);});

test('comanda respeita os serviços habilitados do profissional',()=>{const s=orderBase();assert.throws(()=>action(s,'order.item',{id:s.orders[0].id,kind:'service',referenceId:'s4',quantity:1}),/não realiza/);});
